modified action file
to call omidot api

diff --git a/.github/actions/godot-api-dump/action.yml b/.github/actions/godot-api-dump/action.yml
--- a/.github/actions/godot-api-dump/action.yml
+++ b/.github/actions/godot-api-dump/action.yml
@@ -1,25 +1,39 @@
-name: Dump Godot API
-description: Dump Godot API for GDExtension
+name: Dump Omidot API
+description: Dump Omidot API for GDExtension
 
 inputs:
   bin:
-    description: The path to the Godot executable
+    description: The path to the Omidot executable
     required: true
 
 runs:
   using: composite
   steps:
     # Dump GDExtension interface and API
-    - name: Dump GDExtension interface and API for godot-cpp build
+    - name: Dump GDExtension interface and API for omidot-cpp build
       shell: sh
       run: |
+        if [ ! -f "${{ inputs.bin }}" ]; then
+          echo "Executable not found: ${{ inputs.bin }}"
+          exit 1
+        fi
         ${{ inputs.bin }} --headless --dump-gdextension-interface --dump-extension-api
-        mkdir godot-api
-        cp -f gdextension_interface.h godot-api/
-        cp -f extension_api.json godot-api/
+        mkdir -p omidot-api
+        if [ -f "gdextension_interface.h" ]; then
+          cp -f gdextension_interface.h omidot-api/
+        else
+          echo "gdextension_interface.h not found"
+          exit 1
+        fi
+        if [ -f "extension_api.json" ]; then
+          cp -f extension_api.json omidot-api/
+        else
+          echo "extension_api.json not found"
+          exit 1
+        fi
 
     - name: Upload API dump
-      uses: ./.github/actions/upload-artifact
+      uses: actions/upload-artifact@v2
       with:
-        name: godot-api-dump
-        path: ./godot-api/*
+        name: omidot-api-dump
+        path: ./omidot-api/*
